# Generated by Django 5.1.5 on 2025-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('piñatas', 'Piñatas'), ('muñecos', 'Muñecos'), ('stickers', 'Stickers'), ('others', 'Others')], default='others', max_length=255),
        ),
    ]
