# Generated by Django 5.1.5 on 2025-02-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIMain', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('piñatas-niño', 'Piñatas-niño'), ('piñatas-niña', 'Piñatas-niña'), ('piñatas-adulto', 'Piñatas-adulto'), ('porcelanicron-matrimonio', 'Porcelanicron-matrimonio'), ('porcelanicron-quinceañeras', 'Porcelanicron-quinceañeras'), ('porcelanicron-animados', 'Porcelanicron-animados'), ('porcelanicron-profesiones', 'Porcelanicron-profesiones'), ('porcelanicron-comunion', 'Porcelanicron-comunion'), ('porcelanicron-grados', 'Porcelanicron-grados'), ('stickers-niño', 'Stickers-niño'), ('stickers-niña', 'Stickers-niña'), ('stickers-adulto', 'Stickers-adulto'), ('toppers-cumpleanos', 'Toppers-cumpleanos'), ('toppers-feliz-dia', 'Toppers-feliz-dia'), ('toppers-aniversario', 'Toppers-aniversario'), ('toppers-grados', 'Toppers-grados'), ('toppers-comunion', 'Toppers-comunion'), ('toppers-numeros', 'Toppers-numeros')], default='others', max_length=255),
        ),
    ]
